### ISSUE TITLE
The JSON-schema needs additional context to support vendor interfaces and extensions

### ISSUE THREAD

**Issue by nadinemalcolm** [opendi-org/json-schema#1]
There is a layer on top of this JSON.  The interop standard needs to be aware of the context in which the interop is being used, in the following sense: there are some elements that are needed to convey information about CDMs, e.g. a list of elements, how they're defined, what they contain, some rules about how you execute them, etc. These are the focus of the standard.

There are other aspects of the JSON where you are interfacing with the vendor's existing models of things, e.g., the reference to the creator of the CDM: presumably that's a reference to a user who needs to be authenticated. But there are many different ways to create user IDs and many authentication mechanisms, where users are modeled in various ways. We expect that user ID creation and authentication will be vendor-specific. If one mechanism is specified in the standard, some vendors will either reject the standard or violate it. This devalues the standard.

So, we need to specify, probably with a diagram, the standard's areas of responsibility and the places it interfaces with existing models. There may also be some optional parts of the standard.

So, there are:

1. Things we mandate or insist on.
2. Optional things we support , but do not mandate.
3. Things that are vendor-defined.

There will be vendor-defined things that add properties to things we mandate or support. So, we need to have a place like "properties" "vendor_properties" where vendors can put their vendor-specific information.

*Submitted by Nadine Malcolm for Mark Zangari*

**Comment by ProfDavidRoberts** [comment]
Notes from discussion (@nadinemalcolm, @markzangari, @jeselgroth, @isaac-kellogg-quantellia, @ProfDavidRoberts, @LYPratt):
* "What is the essential part of the information interchange we control, and how do we provide enough flexibility for vendors to add proprietary information that piggy backs on it?"
* Schemas can define named objects without specifying the contents of it
* Users can put proprietary data into properties 
* Can look at the schema elements that have been defined so far

Example: current draft has a required property called "partialRetrieval"

JSON Schemas have 3 types of semantics
1. Closed world: anything that is not explicitly included in the Schema is not allowed
2. Open world: anything that is not explicitly included in the Schema is allowed
3. Middle-ground: anything not explicitly in the Schema may be included provided it adheres to a loose structure

Being too open can lead to namespace collisions, so selecting "closed world" but providing a catch-all vendor specific area makes sense. 
* Need some minimal level of control over this
* Want to avoid the inevitable mess of namespace collisions 
* Somethings may be "enforced" by convention, rather than schema requirements 
* Can use descriptions in the Schema to suggest best practices or convention, but not enforce those things 
* Should provide some examples

Will create a working group to implement this in the draft.

**Comment by isaac-kellogg-quantellia** [comment]
Additional notes from discussion with Mark and Nadine on 2024-07-22:

Discussion centered around different use cases / contexts for the schema, and considering properties in the context of the 3 roughly categorical "things" Nadine mentioned in the initial issue description.

A couple of specific use cases motivated the changes we ultimately discussed making.  
I've spun these out into new issues, to avoid overloading this topic:  
- #5 
- #6 

For this issue specifically, I will consider it complete when:
- The schema's areas of responsibility are more clearly defined
- There are explicit mechanisms within the schema for stakeholder-specific expansion, in a controlled way that balances permissiveness with maintainability
